name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: unit-test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt clippy
          rustc --version
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --all

      - name: Run linters
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
